# Generated by Django 4.2.2 on 2023-06-14 11:10

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portefolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, upload_to='portfolio_covers/')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('developer', 'name'), unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Portefolio',
            },
        ),
    ]
